version: '3.8'

services:
  scraper:
    build: .
    ports:
      - "${PORT:-6061}:${PORT:-6061}"
    environment:
      - NODE_ENV=production
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - USE_PROXY=${USE_PROXY:-false}
      - PROXY_URL=${PROXY_URL:-}
      - PORT=${PORT:-6061}
    # Add healthcheck to ensure the service is running properly
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:${PORT:-6061}"]
      interval: 30s
      timeout: 10s
      retries: 3
    # Restart policy for production
    restart: unless-stopped